### ISSUE TITLE
Sticky header not working sometimes

### ISSUE THREAD

**Issue by YuraVolk** [YuraVolk/Js-Library#29]
**Describe the bug**
Sticky header not becomes sticky
when scrolled out of view.

**To Reproduce**
1. Go to sticky header.
2. Start scrolling up and down
3. Error

**Expected behavior**
Header should change its position to sticky.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 81

**Comment by Litvinenko-Yury** [comment]
Это чего, мне тут чего-нибудь делать? 8-/

**Comment by YuraVolk** [comment]
Even though issue is proved to be
wrong, I am disapproving it right now.
Issue is proved to be real.

I am attaching video to make sure
for everyone issue is real.

[https://drive.google.com/open?id=1QkYJxzSrs3cxIOaUmbsgoj4mWKjUFhcf](Video)

**Comment by YuraVolk** [comment]
The reason of sticky header 
solves using CTRL+R.
Closing and marking issue wrong again.
