### ISSUE TITLE
Select Script Improvement

### ISSUE THREAD

**Issue by YuraVolk** [YuraVolk/Js-Library#30]
**Is your feature request related to a problem? Please describe.**
Add custom styles for header of custom select.

**Describe the solution you'd like**
Header changes its style 

**Additional context**
BEM for classes.

**Comment by YuraVolk** [comment]
Custom styles were added

**Comment by YuraVolk** [comment]
Features are done now.
Only semantic is left.

**Comment by Litvinenko-Yury** [comment]
Not BEM.

**Comment by Litvinenko-Yury** [comment]
И еще нужно добавить атрибуты для select, что-бы на сервер отсылались корректные данные.
Пример:
 <div class="custom-select">
          <select name="status">
            <option value="любой" selected>Предприниматель</option>
            <option value="средний">Начальник</option>
            <option value="большой">Важный начальник</option>
            <option value="очень__большой">Круче меня только горы</option>
          </select>
        </div>
