### ISSUE TITLE
Blocks fell out of parent - Filtering on JS

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#33]
**Describe the bug**
Blocks fell out of parent - Filtering on JS

**To Reproduce**
width < 1550px

**Expected behavior**
Blocks should change their position
in vertical alignment. The smaller
size of screen, the more height of container
is.

**Screenshots**
https://monosnap.com/file/q1wKHJSHwyBO6zDQWxDymHhV8y05jv

**Desktop (please complete the following information):**
 - OS: ***
 - Browser ***
 - Version ***

**Smartphone (please complete the following information):**
no

**Additional context**
no

***Links***
no

**Comment by YuraVolk** [comment]
Блоки не резиновые. 
Без резиновости естественно выходит.
Проверьте, скачав библиотеку и сделав их резиновыми.
И контейнер резиновым тоже.

**Comment by Litvinenko-Yury** [comment]
Блоки не должны выпадать из родителя. Резиновость здесь не причем. 
У .filter родитель .block__description.
Вот .filter и должен быть не шире родителя.
А при изменении ширины .filter будут перестраиваться внутренние элементы.

**Comment by YuraVolk** [comment]
Это адаптивность. 
Разве нет?

**Comment by Litvinenko-Yury** [comment]
нет.

**Comment by YuraVolk** [comment]
То есть, это проблема в скрипте?

**Comment by Litvinenko-Yury** [comment]
.filter задана жестко ширина 1210px, поэтому так и происходит.

**Comment by Litvinenko-Yury** [comment]
нет, скрипт не при чем

**Comment by YuraVolk** [comment]
Объясните в чем проблема.
То есть на выбор из

1. HTML
2. CSS
3. JS

**Comment by Litvinenko-Yury** [comment]
CSS

**Comment by YuraVolk** [comment]
Предлагаю редакцию проблемы.
В Expected behavior подробно
и пошагово описать то, как 
должно работать правильное решение.

**Comment by Litvinenko-Yury** [comment]
.filter {
width: 100%;
}

или вообще удалить ширину ему.
В зависимости от желаемого поведения.

**Comment by YuraVolk** [comment]
Понятно.
Редакция успешна.

**Comment by YuraVolk** [comment]
Последующие комментарии не принимаются в рассмотрение.
