### ISSUE TITLE
Warning! Filtering on JS - CSS-style in html

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#34]
**Describe the bug**
Filtering on JS - CSS-style in html

**To Reproduce**
DevTools

**Expected behavior**

**Screenshots**
https://monosnap.com/file/pNkQbmpXZJTO39GIoulrGp3PUmvmTS

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
no

**Additional context**
Styles should be added by the class.

***Links***
no

**Comment by YuraVolk** [comment]
Ok
