### ISSUE TITLE
ERROR! Videoset on JS  -   wrong markup.

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#35]
**Describe the bug**
Videoset on JS  -   wrong markup.
- no logic in building indoor units
- no BEM

**To Reproduce**
DevTools.

**Expected behavior**
Тhe structure should allow taking the BEM block of the library with class names and use in another project.

**Screenshots**
no

**Desktop (please complete the following information):**
 no

**Smartphone (please complete the following information):**
no

**Additional context**
redo markup and set class names by BEM

***Links***
no

**Comment by YuraVolk** [comment]
Итак, что имеется в виду под
no logic in building indoor units

**Comment by Litvinenko-Yury** [comment]
нет логики в разметке внутренних блоков.

**Comment by YuraVolk** [comment]
Это проблема HTML?

**Comment by Litvinenko-Yury** [comment]
ну да.
Нужно его переделать не много, и БЭМ добавить.
Тогда будет логично и появится обособленный БЭМ-блок, который можно быстро вставлять на другую страницу и все будет работать.
