### ISSUE TITLE
WARNING! full error in makeup with disable JS

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#38]
**Describe the bug**
disable JS - makeup crach.

**To Reproduce**

1. Go to 'DevTools - Setting - Debugger'
2. Desable JS
3. update page

**Expected behavior**
Page layout should not be crach.

**Screenshots**
https://monosnap.com/file/d4lshdV14AtCFQ7ZjrgLZmE7e93Bdj

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 79

**Smartphone (please complete the following information):**
 - 

**Additional context**
((((

***Links***

**Comment by YuraVolk** [comment]
Ok.
