### ISSUE TITLE
Обращение к элементу каскадом.

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#51]
.custom-select > select {
}

Здесь используется обращение к элементу каскадом.
Более "феншуестее" обратиться по классу. Для этого нужно дать класс для тега select.
Конечно, т.к. внутри custom-select всегда будет тег select, такая конструкция очень надежна.
Поэтому тут 50/50.
Возможно, имя класса для тега select пригодится для того, чтобы можно было давать модификатор для тега select и стилизовать разные select на странице по разному?

**Comment by YuraVolk** [comment]
Но к тегу селект можно добавить select.custom-class-2 например.
