### ISSUE TITLE
custom-select отправка данныйх на сервер.

### ISSUE THREAD

**Issue by Litvinenko-Yury** [YuraVolk/Js-Library#52]
Что отправится на сервер в случае custom-select?
Там ведь нет <option value="test2" class="">Test 2</option> и т.д.?
Т.е. на сервер не отправится value="test2"  и т.п.?

**Comment by YuraVolk** [comment]
![Uploading Запись_2020_01_26_09_19_20_236.gif…](Видео)

Все работает.
